server:
  port: 7078

spring:
  application:
    name: springactional
  datasource:
    url: jdbc:postgresql://localhost:5432/springactional?currentSchema=transactional
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true